facts = {
    "Afghanistan": "Afghanistan is home to the world's oldest known oil paintings, found in the Bamiyan caves.",
    "Albania": "Albania is known as the 'Land of Eagles' and has a double-headed eagle on its flag.",
    "Algeria": "Algeria is the largest country in Africa by land area.",
    "Andorra": "Andorra has no airport; the nearest airports are in Spain and France.",
    "Angola": "Angola is the second largest Portuguese-speaking country in the world.",
    "Antigua and Barbuda": "Antigua has 365 beaches, one for every day of the year.",
    "Argentina": "Argentina is the birthplace of the tango dance and music.",
    "Armenia": "Armenia was the first country to adopt Christianity as its state religion.",
    "Australia": "Australia is home to the Great Barrier Reef, the largest coral reef system in the world.",
    "Austria": "Austria is famous for its classical music composers, including Mozart and Beethoven.",
    "Azerbaijan": "Azerbaijan is known as the 'Land of Fire' due to its natural gas reserves that cause continuous flames.",
    "Bahamas": "The Bahamas is home to the world's third largest barrier reef.",
    "Bahrain": "Bahrain is an archipelago of 33 islands.",
    "Bangladesh": "Bangladesh is known for having the world's largest river delta, the Sundarbans, which is also home to the Bengal tiger.",
    "Barbados": "Barbados is often referred to as 'Little England' due to its long association with Britain.",
    "Belarus": "Belarus is known as the 'lungs of Europe' because it is one of the most forested countries on the continent.",
    "Belgium": "Belgium is famous for its chocolate, with over 2,000 chocolatiers in the country.",
    "Belize": "Belize has the second largest barrier reef in the world, after Australia.",
    "Benin": "Benin is considered the birthplace of the Vodun (Voodoo) religion.",
    "Bhutan": "Bhutan measures its success by Gross National Happiness instead of Gross Domestic Product.",
    "Bolivia": "Bolivia is home to the Salar de Uyuni, the world's largest salt flat.",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina has a unique coffee culture that is deeply rooted in social gatherings.",
    "Botswana": "Botswana is home to the Okavango Delta, one of the world's largest inland deltas.",
    "Brazil": "Brazil is the largest country in South America and the only Portuguese-speaking country in the Americas.",
    "Brunei": "Brunei is one of the richest countries in the world due to its extensive petroleum and natural gas fields.",
    "Bulgaria": "Bulgaria is one of the oldest countries in Europe and has never changed its name since it was first established.",
    "Burkina Faso": "Burkina Faso hosts one of the largest crafts markets in Africa, the International Crafts Fair of Ouagadougou.",
    "Burundi": "Burundi is known as the 'Heart of Africa' due to its central location on the African continent.",
    "Cabo Verde": "Cabo Verde consists of 10 volcanic islands in the central Atlantic Ocean.",
    "Cambodia": "Cambodia is home to Angkor Wat, the largest religious monument in the world.",
    "Cameroon": "Cameroon is known as 'Africa in Miniature' because it has all the major climates and vegetation of the continent.",
    "Canada": "Canada has the longest coastline of any country in the world.",
    "Central African Republic": "The Central African Republic is home to some of the world's oldest human fossils, dating back 2.5 million years.",
    "Chad": "Chad's Lake Chad is one of the largest lakes in Africa and supports over 20 million people.",
    "Chile": "Chile is the longest north-south trending country in the world, stretching over 4,300 km.",
    "China": "China has the world's largest population, with over 1.4 billion people.",
    "Colombia": "Colombia is the world's leading source of emeralds.",
    "Comoros": "Comoros is one of the least populous countries in the world, with fewer than a million people.",
    "Democratic Republic of the Congo": "The Congo River in the Democratic Republic of the Congo is the deepest river in the world.",
    "Congo": "The Republic of the Congo is home to the second largest rainforest in the world.",
    "Costa Rica": "Costa Rica is known for its biodiversity, with over 500,000 species of wildlife.",
    "Croatia": "Croatia's Dalmatian coast is home to more than 1,000 islands.",
    "Cuba": "Cuba is the largest island in the Caribbean.",
    "Cyprus": "Cyprus is known as the birthplace of the ancient Greek goddess of love, Aphrodite.",
    "Czech Republic": "The Czech Republic has the highest beer consumption per capita in the world.",
    "Denmark": "Denmark is consistently ranked as one of the happiest countries in the world.",
    "Djibouti": "Djibouti is home to Lake Assal, the lowest point in Africa.",
    "Dominica": "Dominica is known as the 'Nature Island' of the Caribbean for its lush landscapes and natural hot springs.",
    "Dominican Republic": "The Dominican Republic is the site of the oldest European settlement in the Americas, Santo Domingo.",
    "Ecuador": "Ecuador is named after the equator, which runs through the country.",
    "Egypt": "Egypt is home to the Great Pyramid of Giza, one of the Seven Wonders of the Ancient World.",
    "El Salvador": "El Salvador is known as the 'Land of Volcanoes' due to its frequent seismic activity.",
    "Equatorial Guinea": "Equatorial Guinea is the only country in Africa where Spanish is the official language.",
    "Eritrea": "Eritrea has one of the highest archaeological densities in the world.",
    "Estonia": "Estonia is one of the most digitally advanced countries, offering e-residency to people worldwide.",
    "Eswatini": "Eswatini, formerly known as Swaziland, is one of the last absolute monarchies in the world.",
    "Ethiopia": "Ethiopia is the only African country never to have been colonized.",
    "Fiji": "Fiji consists of more than 330 islands, about a third of which are inhabited.",
    "Finland": "Finland is known as the 'Land of a Thousand Lakes,' with around 188,000 lakes.",
    "France": "France is the most visited country in the world, with over 89 million tourists annually.",
    "Gabon": "Gabon is home to 80% of Africa's gorilla population.",
    "Gambia": "Gambia is the smallest country on mainland Africa.",
    "Georgia": "Georgia is home to the world's oldest known wine-making tradition, dating back 8,000 years.",
    "Germany": "Germany is known for its famous Oktoberfest, the world's largest beer festival.",
    "Ghana": "Ghana was the first African country to gain independence from colonial rule in 1957.",
    "Greece": "Greece is known as the cradle of Western civilization and democracy.",
    "Grenada": "Grenada is known as the 'Island of Spice' for its production of nutmeg and mace.",
    "Guatemala": "Guatemala is home to the ancient Maya city of Tikal, one of the largest archaeological sites in Mesoamerica.",
    "Guinea": "Guinea is one of the world's largest producers of bauxite, the ore used to make aluminum.",
    "Guinea-Bissau": "Guinea-Bissau is known for its rich biodiversity and national parks, including the Bijagos Archipelago.",
    "Guyana": "Guyana is the only English-speaking country in South America.",
    "Haiti": "Haiti was the first independent nation in Latin America and the Caribbean, and the first post-colonial independent black-led nation in the world.",
    "Honduras": "Honduras is home to the ancient ruins of Copán, a major Maya city.",
    "Hungary": "Hungary has one of the oldest and most prestigious wine regions, Tokaj, known for its sweet Tokaji wine.",
    "Iceland": "Iceland is known as the 'Land of Fire and Ice' due to its volcanoes and glaciers.",
    "India": "India is the birthplace of four major world religions: Hinduism, Buddhism, Jainism, and Sikhism.",
    "Indonesia": "Indonesia is the world's largest archipelago, consisting of over 17,000 islands.",
    "Iran": "Iran is home to the world's oldest continuous major civilization, dating back to 7000 BC.",
    "Iraq": "Iraq is known as the cradle of civilization, with ancient Mesopotamia being one of the earliest human societies.",
    "Ireland": "Ireland is known as the 'Emerald Isle' for its lush green landscapes.",
    "Israel": "Israel has the highest number of museums per capita in the world.",
    "Italy": "Italy is home to the most UNESCO World Heritage Sites of any country in the world.",
    "Jamaica": "Jamaica is the birthplace of reggae music and the Rastafari movement.",
    "Japan": "Japan has the world's oldest continuously operating company, Kongō Gumi, which was founded in 578 AD.",
    "Jordan": "Jordan is home to the ancient city of Petra, one of the New Seven Wonders of the World.",
    "Kazakhstan": "Kazakhstan is the largest landlocked country in the world.",
    "Kenya": "Kenya is famous for its wildlife and is home to the 'Big Five' animals.",
    "Kiribati": "Kiribati is the only country that spans all four hemispheres.",
    "Kuwait": "Kuwait has the sixth largest oil reserves in the world.",
    "Kyrgyzstan": "Kyrgyzstan is home to the world's largest natural walnut forest, the Arslanbob Forest.",
    "Laos": "Laos is the most heavily bombed country per capita in history, due to the Vietnam War.",
    "Latvia": "Latvia has one of the fastest internet speeds in the world.",
    "Lebanon": "Lebanon is one of the world's oldest countries, with evidence of civilization dating back more than 7,000 years.",
    "Lesotho": "Lesotho is the only country in the world to be entirely above 1,000 meters in elevation.",
    "Liberia": "Liberia is Africa's oldest republic, founded by freed American slaves.",
    "Libya": "Libya has the largest proven oil reserves in Africa.",
    "Liechtenstein": "Liechtenstein is one of the world's two doubly landlocked countries, meaning it is surrounded by landlocked countries.",
    "Lithuania": "Lithuania was the first Soviet republic to declare independence in 1990.",
    "Luxembourg": "Luxembourg is the second richest country in the world by GDP per capita.",
    "Madagascar": "Madagascar is home to 5% of the world's plant and animal species, 80% of which are not found anywhere else.",
    "Malawi": "Malawi is known as the 'Warm Heart of Africa' for its friendly people.",
    "Malaysia": "Malaysia is home to the world's tallest twin towers, the Petronas Towers.",
    "Maldives": "The Maldives is the lowest country in the world, with an average ground level of just 1.5 meters above sea level.",
    "Mali": "Mali was home to the wealthy Mali Empire and its famous ruler, Mansa Musa, often considered the richest person in history.",
    "Malta": "Malta has three UNESCO World Heritage Sites, including the Megalithic Temples which are some of the oldest free-standing structures in the world.",
    "Marshall Islands": "The Marshall Islands have more than 1,100 islands and islets.",
    "Mauritania": "Mauritania is home to the Richat Structure, also known as the Eye of the Sahara, a prominent circular feature in the desert.",
    "Mauritius": "Mauritius was the only known habitat of the now-extinct dodo bird.",
    "Mexico": "Mexico is home to the world's largest pyramid, the Great Pyramid of Cholula.",
    "Micronesia": "Micronesia is composed of 607 islands spread across the western Pacific Ocean.",
    "Moldova": "Moldova is one of the least visited countries in Europe.",
    "Monaco": "Monaco is the second smallest country in the world, after Vatican City.",
    "Mongolia": "Mongolia is the least densely populated country in the world.",
    "Montenegro": "Montenegro has one of the world's most beautiful bays, the Bay of Kotor.",
    "Morocco": "Morocco's city of Fez is home to the world's oldest existing, continually operating educational institution, the University of Al Quaraouiyine.",
    "Mozambique": "Mozambique's flag is the only national flag with a modern weapon, an AK-47, on it.",
    "Burma": "Burma is home to the Shwedagon Pagoda, which is covered with hundreds of gold plates and topped with thousands of diamonds.",
    "Namibia": "Namibia is home to the world's oldest desert, the Namib Desert.",
    "Nauru": "Nauru is the smallest island country in the world.",
    "Nepal": "Nepal is the only country with a non-rectangular flag.",
    "Netherlands": "The Netherlands is known for having more bicycles than people.",
    "New Zealand": "New Zealand was the first country to grant women the right to vote in 1893.",
    "Nicaragua": "Nicaragua is known as the 'Land of Lakes and Volcanoes.'",
    "Niger": "Niger is named after the Niger River, the third longest river in Africa.",
    "Nigeria": "Nigeria is the most populous country in Africa.",
    "North Korea": "North Korea is one of the most secretive and isolated countries in the world.",
    "North Macedonia": "North Macedonia is home to the oldest lake in Europe, Lake Ohrid.",
    "Norway": "Norway is known for its stunning fjords, carved by glaciers over thousands of years.",
    "Oman": "Oman has the oldest independent state in the Arab world.",
    "Pakistan": "Pakistan is home to the world's second highest peak, K2.",
    "Palau": "Palau has one of the world's largest marine sanctuaries.",
    "Panama": "Panama is the only place in the world where you can see the sun rise on the Pacific and set on the Atlantic.",
    "Papua New Guinea": "Papua New Guinea has the most languages of any country, with over 850 indigenous languages.",
    "Paraguay": "Paraguay is home to the world's largest rodent, the capybara.",
    "Peru": "Peru is home to Machu Picchu, an ancient Incan city in the Andes Mountains.",
    "Philippines": "The Philippines is made up of over 7,000 islands.",
    "Poland": "Poland is home to the world's largest castle, Malbork Castle.",
    "Portugal": "Portugal is the oldest nation state on the Iberian Peninsula and one of the oldest in Europe.",
    "Qatar": "Qatar is the richest country in the world by GDP per capita.",
    "Romania": "Romania is home to the world's heaviest building, the Palace of the Parliament.",
    "Russia": "Russia is the largest country in the world by land area.",
    "Rwanda": "Rwanda is known as the 'Land of a Thousand Hills' for its mountainous terrain.",
    "Saint Kitts and Nevis": "Saint Kitts and Nevis is the smallest country in the Americas both in area and population.",
    "Saint Lucia": "Saint Lucia is the only country named after a woman, Saint Lucy of Syracuse.",
    "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines has the oldest botanical gardens in the Western Hemisphere.",
    "Samoa": "Samoa is known for its beautiful waterfalls and lush rainforests.",
    "San Marino": "San Marino is the world's oldest republic, founded in 301 AD.",
    "Sao Tome and Principe": "Sao Tome and Principe is Africa's second smallest country by population.",
    "Saudi Arabia": "Saudi Arabia is home to the world's largest sand desert, the Rub' al Khali or Empty Quarter.",
    "Senegal": "Senegal is home to the African Renaissance Monument, the tallest statue in Africa.",
    "Serbia": "Serbia is home to the highest number of Roman emperors born in any country, with 18 out of 69.",
    "Seychelles": "Seychelles is home to two UNESCO World Heritage Sites, Aldabra Atoll and Vallée de Mai.",
    "Sierra Leone": "Sierra Leone is known for its beautiful beaches and rich diamond mines.",
    "Singapore": "Singapore is one of the world's greenest cities, with nearly half of its area covered in greenery.",
    "Slovakia": "Slovakia is home to more than 6,000 caves.",
    "Slovenia": "Slovenia has one of the world's most sustainable tourism models, focusing on eco-friendly travel.",
    "Solomon Islands": "The Solomon Islands were a major battleground during World War II, including the Battle of Guadalcanal.",
    "Somalia": "Somalia has the longest coastline in mainland Africa.",
    "South Africa": "South Africa has three capital cities: Pretoria, Cape Town, and Bloemfontein.",
    "South Korea": "South Korea is known for its advanced technology and the fastest internet speeds in the world.",
    "South Sudan": "South Sudan is the youngest country in the world, having gained independence in 2011.",
    "Spain": "Spain is home to the world's oldest restaurant, Sobrino de Botín, which opened in 1725.",
    "Sri Lanka": "Sri Lanka is known as the 'Pearl of the Indian Ocean' for its natural beauty.",
    "Sudan": "Sudan has more pyramids than Egypt, with over 200 in the region of Nubia.",
    "Suriname": "Suriname is the smallest country in South America by land area.",
    "Sweden": "Sweden is known for its 'right to roam' laws, allowing public access to private land for recreation.",
    "Switzerland": "Switzerland is famous for its neutrality, not having been in a state of war since 1815.",
    "Syria": "Syria is home to some of the oldest continuously inhabited cities in the world, including Damascus and Aleppo.",
    "Taiwan": "Taiwan is known for its night markets and delicious street food.",
    "Tajikistan": "Tajikistan is home to the world's second highest dam, the Nurek Dam.",
    "Tanzania": "Tanzania is home to Mount Kilimanjaro, the highest peak in Africa.",
    "Thailand": "Thailand is the only Southeast Asian country that was never colonized by a European power.",
    "Timor-Leste": "Timor-Leste is one of the world's newest countries, gaining independence in 2002.",
    "Togo": "Togo is one of the world's largest producers of phosphates.",
    "Tonga": "Tonga is the only Pacific nation never to have been colonized.",
    "Trinidad and Tobago": "Trinidad and Tobago is the birthplace of the steelpan drum.",
    "Tunisia": "Tunisia is home to the ancient city of Carthage, a major power in the ancient Mediterranean.",
    "Turkey": "Turkey is home to two of the Seven Wonders of the Ancient World, the Temple of Artemis and the Mausoleum at Halicarnassus.",
    "Turkmenistan": "Turkmenistan is home to the 'Door to Hell,' a natural gas field that has been burning continuously since 1971.",
    "Tuvalu": "Tuvalu is the second least populous country in the world, after Vatican City.",
    "Uganda": "Uganda is known as the 'Pearl of Africa' for its stunning natural beauty and biodiversity.",
    "Ukraine": "Ukraine is the largest country entirely within Europe.",
    "United Arab Emirates": "The Burj Khalifa in the United Arab Emirates is the tallest building in the world.",
    "United Kingdom": "The United Kingdom is home to the oldest royal residence still in use, Windsor Castle.",
    "United States of America": "The United States has the world's largest economy.",
    "Uruguay": "Uruguay was the first country to provide a laptop for every primary school student.",
    "Uzbekistan": "Uzbekistan is one of only two double landlocked countries in the world.",
    "Vanuatu": "Vanuatu is one of the most linguistically diverse countries, with over 100 indigenous languages spoken.",
    "Vatican City": "Vatican City is the smallest country in the world by both area and population.",
    "Venezuela": "Venezuela is home to the world's highest waterfall, Angel Falls.",
    "Vietnam": "Vietnam is the largest exporter of cashew nuts and black pepper.",
    "Yemen": "Yemen is home to the ancient skyscraper city of Shibam, known as the 'Manhattan of the Desert.'",
    "Zambia": "Zambia is home to Victoria Falls, one of the largest and most famous waterfalls in the world.",
    "Zimbabwe": "Zimbabwe is home to the Great Zimbabwe Ruins, the remains of an ancient city from the Kingdom of Zimbabwe.",
}

countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burma",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]
